### ISSUE TITLE
Use B and C instead of 0xF000 and 0xF001 to pass arguments to the interrupt handler

### ISSUE THREAD

**Issue by L3nn0x** [FrOSt-Foundation/cFrOSt#17]

**Comment by Yamakaky** [comment]
B and C should be sufficient, you can always pass a struct if you want.
For the return value, A is poped, so we can't use it.

**Comment by L3nn0x** [comment]
We can use B and C for return arguments too

**Comment by azertyfun** [comment]
Fixed by 0f105c54eb3881928d85f34ea231de881268b255
