### ISSUE TITLE
TC Usage

### ISSUE THREAD

**Issue by paultech** [FrOSt-Foundation/cFrOSt#30]
Hey guys,

Working to get this package in our deployment tools so we can auto-build the latest version for distribution. Do you see this program available as a floppy disk? It's own ROM(Seems most logical for a OS)? Is any compatibility with BBOS expected? Will there be a installer floppy to copy it to ROM?

Thanks guys! Excited to see it in game

**Comment by Yamakaky** [comment]
To build it, you just have to run `make`, then take `bin/cFrOSt.bin`. I think a floppy would be appropriate, you just have to copy the ROM on RAM at 0.

**Comment by paultech** [comment]
Understand the build process ok!
 More how you envision people use it in game?  To use cFrost on a DCPU on your stations - What's your desired process? A rom with cFrost pre-installed that can be placed in the DCPU frame? A installer floppy that self-copies to ROM? A floppy that required to be inserted each time to boot cFrost?

**Comment by azertyfun** [comment]
FrOSt should be able to run from any medium as long as it is loaded into the RAM by something else.

We have created a [bbos-compatible bootloader](https://github.com/FrOSt-Foundation/cFrOSt/blob/indev/src/FrOSt_header.dasm) (available after `make` in bin/FrOSt.bin), but you should theoretically be able to use MadMockers' tool to create a floppy with bin/FrOSt.bin.

An installer floppy is a possibility, we have yet to implement ROM support in our emulator so that's why it isn't a thing. However, FrOSt works when loaded as a ROM directly.

**Comment by Yamakaky** [comment]
Edit: the bootloader is in `bin/FrOSt_header.bin`

As for now, there is no installation process, you just launch the OS, so it doesn't matter.

**Comment by paultech** [comment]
Sorry, i may not of been clear!  I'd include to include Frost as a default package in game, there fore it should be easy for the player to get up and running without leaving the game. I'd be happy to create a installer floppy that works with BBoS to copy FroST to the installed ROM. So users can easily install FroST on any DCPU they wish.

**Comment by azertyfun** [comment]
We have yet to see how it works in-game exactly, but the medium isn't something that matters much for now.

If what you are suggesting is easily doable, then go ahead!

**Comment by paultech** [comment]
Thank you! 
Will update you guys via IRC on the progress today. Given the build system will auto pull from this repo on new builds of TC - is there a preferred branch I should pull from in the future to ensure I get something stable?

Thanks!

**Comment by Yamakaky** [comment]
We use the indev branch for dev and master for release. Well, in theory, since master is way behind ^^ Tell us when you are ready and we will start to use `master`.

**Comment by paultech** [comment]
We look good to go! Thanks gentlemen
